name: bg_tube
description: Listen youtube to background
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  path_provider: ^2.0.11
  youtube_explode_dart: ^1.12.1
  receive_sharing_intent: ^1.4.5
  move_to_background: ^1.0.2
  cached_network_image: ^3.2.2
  auto_size_text: ^3.0.0
  drop_shadow_image: ^0.9.0
  audio_service: ^0.18.7
  just_audio: ^0.9.30
  audio_video_progress_bar: ^0.11.0
  intl: ^0.17.0
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.6

dependency_overrides:
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_launcher_name: ^0.0.1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/placeholder.png

flutter_launcher_name: #flutter pub run flutter_launcher_name:main
  name: "BgTube"

flutter_icons: #flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  linux:
    generate: false